apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: exercises
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  clusterIP: None
  selector:
    app: postgresapp

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: posgres-stset
  namespace: exercises
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgresapp
  template:
    metadata:
      labels:
        app: postgresapp
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: pingpong-conf
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: pingpong-conf
                  key: postgres_port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: pingpong-conf
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: pingpong-conf
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pingpong-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-data-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
