apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: ipersids/pingpong:ex2.1
          env:
            - name: PORT
              value: "3002"
          ports:
            - name: http
              containerPort: 3002
