apiVersion: v1
kind: Service
metadata:
  name: todopostgres-svc
  namespace: project
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  clusterIP: None
  selector:
    app: todopostgresapp

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todoposgres-stset
  namespace: project
spec:
  serviceName: todopostgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: todopostgresapp
  template:
    metadata:
      labels:
        app: todopostgresapp
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: todobackend-conf
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: todobackend-conf
                  key: postgres_port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todobackend-conf
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: todobackend-conf
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todobackend-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /data/pgdata
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-data-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
