apiVersion: apps/v1
kind: Deployment
metadata:
  name: todobackend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      labels:
        app: todobackend
    spec:
      containers:
        - name: todobackend
          image: ipersids/todobackend:ex2.10
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todobackend-conf
                  key: port
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: todobackend-conf
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: todobackend-conf
                  key: postgres_port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todobackend-conf
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: todobackend-conf
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todobackend-secret
                  key: POSTGRES_PASSWORD
            - name: DB_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
          ports:
            - name: http
              containerPort: 3003
