apiVersion: v1
kind: Service
metadata:
  name: todobackend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todobackend
  ports:
    - name: http
      protocol: TCP
      port: 2348
      targetPort: http
