apiVersion: v1
kind: Secret
metadata:
    name: todobackend-secret
    namespace: project
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:K/QXAvHXHBcHIVYAifQ0UuwQqkG9PqFjbQOfeM/4jnCjZOEqlTPIjw==,iv:tTaZyPbj1XPUVnl3ubVu7nVmyPTVyaqVPH4oMF40R9g=,tag:En2cb0W71haMd4VFdq/WxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYkNyQ3hIdHNPejZrQk43
            Vm5HeXNEejNkbXpaZ3JuMEt4bkd1S0t4bVJvCkZTbDFKdjh6QzRIMHZDNnBkUEFw
            UjM4aGt6OVczZDRtcGc5RExrbUdCNGsKLS0tIDh5MnVsV1NlU21mVzJSa3ZPaHhn
            dDZhSFBXeUE5UmhyU3pxMFluR1N4NncKdhFq9Qrc/BQxpmTF6BExLxFsPyP/VCVH
            r94L0OUGWDROaTY4Z8tmGF9rXqe6WhfVp/cgEkrEBiFiJFtJS0IA9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13h683f5eqydg6jej35ute3mnvncerkcpu7v5jjn2x0r2rxr0fg6q7yl3kc
    encrypted_regex: ^(data)$
    lastmodified: "2026-07-20T09:39:30Z"
    mac: ENC[AES256_GCM,data:W/pKK77GLUcrUcCsuz0n0oPbWrUGXiJhrv+80upppbCxFNV6LoE0pVfBfpL7nRFYphFmm8AULG/rz0MJmbOzLhzuJx93AoGkKAoyWtn7Nx8Okz2HiiOF+TdV/tjEnZjgHwN1OrUijwFejr+grhnLK84ZzM6y4r/MeaqEt/11Wqo=,iv:p1am1eiEuJHSJCSOU1V2BBMYPvmn3JHhRk10hmXwKyI=,tag:XCcLsmVwmOdTtMYNXruxXg==,type:str]
    version: 3.13.2
