FROM busybox:1.38

COPY scripts/create-random-wiki-reading-task.sh /usr/local/bin/create-random-wiki-reading-task.sh

RUN chmod +x /usr/local/bin/create-random-wiki-reading-task.sh

CMD [ "/usr/local/bin/create-random-wiki-reading-task.sh" ]
