apiVersion: v1
kind: Secret
metadata:
    name: pingpong-secret
    namespace: exercises
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:fKv9/iBkEMN+LwD+2+zLBzhy2RfgDHocqqSWWpGNLd/TwIDucuyXkSOarPI=,iv:xZpoOWhfTqD0B6Fd9klGxFD8SQn0ZR2MRUNWOm1hqGc=,tag:fegYZKF8+X/8pQ5Zh6dlXQ==,type:str]
    DB_URL: ENC[AES256_GCM,data:T6KLZfVFHlTqFGgRNLQ3o0BLWNVDSBfJF274VMGgnF/+yD/iMpZb0mTd5LwprBjvFXn2hccgVen+jzNFmF4wT4IYtdR+HxVHpjijAA+TpJYxtErxMj6xp8lIjN9S8OXcJJEBPg==,iv:ElvETRfxntHiFC4xsTZj01C2b1TxtEoPP3WMQh/GgQ4=,tag:bCuAoh9RESMGIVb4+Xxbcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdmlIeEVTclIyRmNjaldT
            VUY1cFFyUlNJdGlwck9UT1ZrUHM0M2pFS1FzCkhRa25OY0xQS0Nrb1QvSjRMNlA5
            UG5tNndSUDgyclFPV2diLytJRGZyS3MKLS0tIHByeElvQVdhSnlpZVBqRHRXNmhW
            R0hsTHFieXFZOC9lVGkzenh6OGFFOVUKn0/Twbbs1UJe+akpw5gdQmBHoHWU5RHT
            nlheJve269HSqqP5hvrvsxzj5baKZaMnEpkNs7ZIdZe9LQaOZolMiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13h683f5eqydg6jej35ute3mnvncerkcpu7v5jjn2x0r2rxr0fg6q7yl3kc
    encrypted_regex: ^(data)$
    lastmodified: "2026-07-17T16:14:32Z"
    mac: ENC[AES256_GCM,data:x4tk1ZhhkdpN2XLG41GLQcwZVtDeapwhOqxq+KJAk5rhrwVtSXLzVfsB/36HCNKXusD75uG2otQtFpWB5L3GvH+8A1Pbb7W1NSCD3Dp4Ws4PmXEDhQg8WkiEfR06YPmU37tKv8dnv6aU+nLCSwmHr/wJFqNIseMoaymfNGkZXyg=,iv:6QA9AvcHJyO8MX0qjw5SNtAdkOpG5q2qwZmom3As8q8=,tag:OTtaYUeYanYGZkw2bTGLxw==,type:str]
    version: 3.13.2
