apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: logoutput-generator
          image: ipersids/logoutput-generator:ex1.10
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"
            - name: "FILE_PATH"
              value: "/usr/src/app/files/log.txt"

        - name: logoutput-reader
          image: ipersids/logoutput-reader:ex2.1
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3001"
            - name: LOGS_PATH
              value: "/usr/src/app/files/log.txt"
            - name: GET_PINGS
              value: "http://pingpong-svc:2347/pings"
          ports:
            - name: http
              containerPort: 3001
