apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: logoutput
          image: ipersids/logoutput:ex1.7

          env:
            - name: PORT
              value: "3001"

          ports:
            - name: http
              containerPort: 3001
