apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: shared-file
          persistentVolumeClaim:
            claimName: file-claim

      containers:
        - name: todoapp
          image: ipersids/todoapp:ex2.10
          volumeMounts:
            - name: shared-file
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todoapp-conf
                  key: port
            - name: "VOLUME_DIR"
              valueFrom:
                configMapKeyRef:
                  name: todoapp-conf
                  key: volume_dir
            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todoapp-conf
                  key: todo_backend_url
          ports:
            - name: http
              containerPort: 3000
